# Generated by Django 3.2.2 on 2021-05-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='user',
            field=models.CharField(default='baby', max_length=255),
            preserve_default=False,
        ),
    ]
